# Podcast Feed Settings

title:          The Evolution Podcast
email:          michael@theevolutionpodcast.com
description:    "Giving sports, entertainment, and business leaders a platform to tell personal and professional stories of their own 'Evolution'."
subtitle:       "Today's best sports, entertainment and business stories"
url:            theevolutionpodcast.com
lang:           en
author:         Michael Spartz
copyright:      "&#x2117; &amp; &#xA9; 2017"
